# Generated by Django 5.2.5 on 2025-08-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bus_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='role',
            field=models.CharField(choices=[('Passenger', 'Passenger'), ('Student', 'Student'), ('Operator', 'Operator')], max_length=10),
        ),
    ]
