# Generated by Django 5.2.5 on 2025-08-30 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_registration_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='registered_date',
        ),
        migrations.RemoveField(
            model_name='route',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='route',
            name='stops',
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_route',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='seat_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='bus_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='fare_per_km',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='operator',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='total_fare',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='operator',
            field=models.ForeignKey(limit_choices_to={'role': 'Operator'}, on_delete=django.db.models.deletion.CASCADE, to='core.registration'),
        ),
        migrations.AlterField(
            model_name='route',
            name='bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.bus'),
        ),
        migrations.AlterField(
            model_name='route',
            name='end_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='start_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
