# Generated by Django 5.2.5 on 2025-08-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_bus_capacity_remove_bus_registered_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='bus',
        ),
        migrations.DeleteModel(
            name='bus',
        ),
        migrations.DeleteModel(
            name='route',
        ),
    ]
