# Generated by Django 5.2.5 on 2025-08-30 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_route_bus_delete_bus_delete_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('bus_number', models.CharField(max_length=50, unique=True)),
                ('bus_route', models.CharField(max_length=200)),
                ('seat_capacity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(limit_choices_to={'role': 'Operator'}, on_delete=django.db.models.deletion.CASCADE, to='core.registration')),
            ],
        ),
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=100)),
                ('bus_number', models.CharField(max_length=50)),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fare_per_km', models.DecimalField(decimal_places=2, default=1.5, max_digits=6)),
                ('total_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bus')),
            ],
        ),
    ]
