# Generated by Django 5.2.5 on 2025-08-30 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bus_route'),
    ]

    operations = [
        migrations.DeleteModel(
            name='route',
        ),
    ]
