# Generated by Django 5.2.5 on 2025-08-30 09:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(editable=False, max_length=100)),
                ('bus_number', models.CharField(editable=False, max_length=20)),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fare_per_km', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('total_fare', models.DecimalField(decimal_places=2, editable=False, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.bus')),
            ],
        ),
    ]
