# Generated by Django 5.2.5 on 2025-08-30 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='bus_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='route',
            name='operator',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='route',
            name='total_fare',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
