# Generated by Django 5.2.5 on 2025-08-30 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_route_bus_number_alter_route_operator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='end_point',
            new_name='end_stop',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='start_point',
            new_name='start_stop',
        ),
    ]
