# Generated by Django 5.2.5 on 2025-08-30 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_end_point_route_end_stop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='distance_km',
            new_name='distance',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='fare_per_km',
            new_name='fare',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='total_fare',
            new_name='total',
        ),
    ]
