# Generated by Django 5.2.5 on 2025-08-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_distance_km_route_distance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
