# Generated by Django 5.2.5 on 2025-08-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_route_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='bus_qrcodes/'),
        ),
    ]
