# Generated by Django 5.2.5 on 2025-09-02 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_bus_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=10, unique=True)),
                ('fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='ticket_qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.bus')),
                ('passenger', models.ForeignKey(limit_choices_to={'role__in': ['Passenger', 'Student']}, on_delete=django.db.models.deletion.CASCADE, to='core.registration')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
            ],
        ),
    ]
