# Generated by Django 5.2.5 on 2025-09-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
