# Generated by Django 5.2.5 on 2025-09-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_registration_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='wallet_balance',
        ),
    ]
